# Generated by Django 4.2.1 on 2023-11-16 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'gene',
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_number', models.IntegerField(unique=True)),
                ('consequence', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'severities',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=100, unique=True)),
                ('transcript_type', models.CharField(max_length=1)),
                ('tsl', models.CharField(blank=True, max_length=255, null=True)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvl.gene')),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(max_length=255, unique=True)),
                ('var_type', models.CharField(choices=[('SNV', 'SNV'), ('M', 'Mitochondrial'), ('SV', 'SV')], max_length=30)),
            ],
            options={
                'db_table': 'variants',
            },
        ),
        migrations.CreateModel(
            name='VariantTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgvsc', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvl.transcript')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvl.variant')),
            ],
            options={
                'db_table': 'variants_transcripts',
            },
        ),
        migrations.CreateModel(
            name='VariantConsequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvl.severity')),
                ('variant_transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvl.varianttranscript')),
            ],
            options={
                'db_table': 'variants_consequences',
            },
        ),
        migrations.CreateModel(
            name='VariantAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgvsp', models.CharField(blank=True, max_length=255, null=True)),
                ('polyphen', models.CharField(blank=True, max_length=255, null=True)),
                ('sift', models.CharField(blank=True, max_length=255, null=True)),
                ('variant_transcript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvl.varianttranscript')),
            ],
            options={
                'db_table': 'variants_annotations',
            },
        ),
        migrations.CreateModel(
            name='SNV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_type', models.CharField(max_length=30)),
                ('length', models.IntegerField()),
                ('chr', models.CharField(max_length=3)),
                ('pos', models.IntegerField()),
                ('ref', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
                ('cadd_intr', models.CharField(blank=True, max_length=255, null=True)),
                ('cadd_score', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('dbsnp_url', models.CharField(blank=True, max_length=511, null=True)),
                ('dbsnp_id', models.CharField(blank=True, max_length=30, null=True)),
                ('ucsc_url', models.CharField(blank=True, max_length=511, null=True)),
                ('ensembl_url', models.CharField(blank=True, max_length=511, null=True)),
                ('clinvar_vcv', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True)),
                ('clinvar_url', models.CharField(blank=True, max_length=511, null=True)),
                ('gnomad_url', models.CharField(blank=True, max_length=511, null=True)),
                ('splice_ai', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvl.variant')),
            ],
            options={
                'db_table': 'snvs',
            },
        ),
        migrations.CreateModel(
            name='GenomicIBVLFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('af_tot', models.DecimalField(decimal_places=10, max_digits=12)),
                ('af_xy', models.DecimalField(decimal_places=10, max_digits=12)),
                ('af_xx', models.DecimalField(decimal_places=10, max_digits=12)),
                ('ac_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ac_xy', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ac_xx', models.DecimalField(decimal_places=3, max_digits=12)),
                ('an_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('an_xy', models.DecimalField(decimal_places=3, max_digits=12)),
                ('an_xx', models.DecimalField(decimal_places=3, max_digits=12)),
                ('hom_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('hom_xy', models.DecimalField(decimal_places=3, max_digits=12)),
                ('hom_xx', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quality', models.DecimalField(decimal_places=3, max_digits=12)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvl.variant')),
            ],
            options={
                'db_table': 'genomic_ibvl_frequencies',
            },
        ),
        migrations.CreateModel(
            name='GenomicGnomadFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('af_tot', models.DecimalField(decimal_places=10, max_digits=12)),
                ('ac_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('an_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('hom_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bvl.variant')),
            ],
            options={
                'db_table': 'genomic_gnomad_frequencies',
            },
        ),
    ]
