# Generated by Django 4.2.13 on 2024-11-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("variome_backend", "0001_initial"),
    ]

    def create_singleton_instance(apps, schema_editor):
        from variome_backend.models.variome_settings import VariomeSettings
        VariomeSettings(site_title="BVL").save()
        
    def remove(apps, schema_editor):
        try:
            from variome_backend.models.variome_settings import VariomeSettings
            VariomeSettings.objects.all().delete()
        except: 
            pass
        
    operations = [
        migrations.RunPython(create_singleton_instance, remove),
    ]
