# Generated by Django 4.2.24 on 2025-12-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("variome_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="variomesettings",
            name="home_page_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
