# Generated by Django 5.2 on 2025-03-26 13:08

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tracking", "0002_auto_20180918_2014"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accesses_per_day", models.IntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Access Configuration",
                "verbose_name_plural": "User Access Configurations",
                "db_table": "user_profile",
            },
        ),
        migrations.CreateModel(
            name="LibraryGroup",
            fields=[],
            options={
                "verbose_name": "User Group",
                "verbose_name_plural": "User Groups",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.group",),
            managers=[
                ("objects", django.contrib.auth.models.GroupManager()),
            ],
        ),
        migrations.CreateModel(
            name="LibraryPageview",
            fields=[],
            options={
                "verbose_name": "Pageview",
                "verbose_name_plural": "Pageviews",
                "permissions": [
                    ("view_tracking_dashboard", "Can view tracking dashboard")
                ],
                "proxy": True,
                "default_permissions": (),
                "indexes": [],
                "constraints": [],
            },
            bases=("tracking.pageview",),
        ),
        migrations.CreateModel(
            name="LibrarySession",
            fields=[],
            options={
                "verbose_name": "Session",
                "verbose_name_plural": "Sessions",
                "proxy": True,
                "default_permissions": (),
                "indexes": [],
                "constraints": [],
            },
            bases=("tracking.visitor",),
        ),
        migrations.CreateModel(
            name="LibraryUser",
            fields=[],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("auth.user",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
