# Generated by Django 4.2.1 on 2024-05-16 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('ibvl', '0001_initial'), ('ibvl', '0002_genomicgnomadfrequency_af_popmax_variant_filter'), ('ibvl', '0003_alter_genomicgnomadfrequency_options_and_more')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'gene',
            },
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity_number', models.IntegerField(unique=True)),
                ('consequence', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'severities',
                'verbose_name_plural': 'Severities',
            },
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_id', models.CharField(max_length=100, unique=True)),
                ('transcript_type', models.CharField(choices=[('E', 'Ensembl'), ('R', 'Refseq')], max_length=1)),
                ('tsl', models.CharField(blank=True, default='', max_length=255)),
                ('gene', models.ForeignKey(db_column='gene', on_delete=django.db.models.deletion.CASCADE, to='ibvl.gene')),
                ('biotype', models.CharField(blank=True, choices=[('protein_coding', 'protein_coding'), ('protein_coding_CDS_not_defined', 'protein_coding_CDS_not_defined'), ('protein_coding_LoF', 'protein_coding_LoF'), ('nonsense_mediated_decay', 'nonsense_mediated_decay'), ('non_stop_decay', 'non_stop_decay'), ('retained_intron', 'retained_intron'), ('processed_transcript', 'processed_transcript'), ('processed_pseudogene', 'processed_pseudogene'), ('pseudogene', 'pseudogene'), ('transcribed_processed_pseudogene', 'transcribed_processed_pseudogene'), ('transcribed_unitary_pseudogene', 'transcribed_unitary_pseudogene'), ('transcribed_unprocessed_pseudogene', 'transcribed_unprocessed_pseudogene'), ('translated_processed_pseudogene', 'translated_processed_pseudogene'), ('TR_C_gene', 'TR_C_gene'), ('TR_D_gene', 'TR_D_gene'), ('TR_J_gene', 'TR_J_gene'), ('TR_J_pseudogene', 'TR_J_pseudogene'), ('TR_V_gene', 'TR_V_gene'), ('TR_V_pseudogene', 'TR_V_pseudogene'), ('unitary_pseudogene', 'unitary_pseudogene'), ('unprocessed_pseudogene', 'unprocessed_pseudogene'), ('IG_C_gene', 'IG_C_gene'), ('IG_C_pseudogene', 'IG_C_pseudogene'), ('IG_D_gene', 'IG_D_gene'), ('IG_J_gene', 'IG_J_gene'), ('IG_J_pseudogene', 'IG_J_pseudogene'), ('IG_pseudogene', 'IG_pseudogene'), ('IG_V_gene', 'IG_V_gene'), ('IG_V_pseudogene', 'IG_V_pseudogene'), ('lncRNA', 'lncRNA'), ('miRNA', 'miRNA'), ('misc_RNA', 'misc_RNA'), ('Mt_rRNA', 'Mt_rRNA'), ('Mt_tRNA', 'Mt_tRNA'), ('ribozyme', 'ribozyme'), ('rRNA', 'rRNA'), ('rRNA_pseudogene', 'rRNA_pseudogene'), ('scaRNA', 'scaRNA'), ('scRNA', 'scRNA'), ('snoRNA', 'snoRNA'), ('snRNA', 'snRNA'), ('sRNA', 'sRNA'), ('vault_RNA', 'vault_RNA'), ('TEC', 'TEC'), ('artifact', 'artifact'), ('', '(unknown)')], default='', max_length=60)),
            ],
            options={
                'db_table': 'transcripts',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_id', models.CharField(max_length=255, unique=True)),
                ('var_type', models.CharField(choices=[('SNV', 'SNV'), ('M', 'Mitochondrial'), ('SV', 'SV')], max_length=30)),
                ('filter', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'db_table': 'variants',
            },
        ),
        migrations.CreateModel(
            name='VariantTranscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgvsc', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript', models.ForeignKey(db_column='transcript', on_delete=django.db.models.deletion.CASCADE, to='ibvl.transcript')),
                ('variant', models.ForeignKey(db_column='variant', on_delete=django.db.models.deletion.CASCADE, to='ibvl.variant')),
            ],
            options={
                'db_table': 'variants_transcripts',
                'verbose_name_plural': 'Variant Transcripts',
            },
        ),
        migrations.CreateModel(
            name='GenomicGnomadFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('af_tot', models.DecimalField(decimal_places=10, max_digits=12)),
                ('ac_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('an_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('hom_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('variant', models.ForeignKey(db_column='variant', on_delete=django.db.models.deletion.CASCADE, to='ibvl.variant')),
                ('af_popmax', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'genomic_gnomad_frequencies',
                'verbose_name_plural': 'Genomic Gnomad Frequencies',
            },
        ),
        migrations.CreateModel(
            name='GenomicIBVLFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('af_tot', models.DecimalField(decimal_places=10, max_digits=12)),
                ('af_xy', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('af_xx', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('ac_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('ac_xy', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('ac_xx', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('an_tot', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('an_xy', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('an_xx', models.DecimalField(decimal_places=3, max_digits=12, null=True)),
                ('hom_tot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('hom_xy', models.DecimalField(decimal_places=3, max_digits=12)),
                ('hom_xx', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quality', models.DecimalField(decimal_places=3, max_digits=12)),
                ('variant', models.ForeignKey(db_column='variant', on_delete=django.db.models.deletion.CASCADE, to='ibvl.variant')),
            ],
            options={
                'db_table': 'genomic_ibvl_frequencies',
                'verbose_name_plural': 'Genomic IBVL Frequencies',
            },
        ),
        migrations.CreateModel(
            name='SNV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('length', models.IntegerField()),
                ('chr', models.CharField(max_length=3)),
                ('pos', models.IntegerField()),
                ('ref', models.CharField(max_length=255)),
                ('alt', models.CharField(max_length=255)),
                ('cadd_intr', models.CharField(blank=True, default='', max_length=255)),
                ('cadd_score', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('dbsnp_url', models.CharField(blank=True, default='', max_length=511)),
                ('dbsnp_id', models.CharField(blank=True, default='', max_length=30)),
                ('ucsc_url', models.CharField(blank=True, default='', max_length=511)),
                ('ensembl_url', models.CharField(blank=True, default='', max_length=511)),
                ('clinvar_vcv', models.DecimalField(decimal_places=3, max_digits=15, null=True)),
                ('clinvar_url', models.CharField(blank=True, default='', max_length=511)),
                ('gnomad_url', models.CharField(blank=True, default='', max_length=511)),
                ('splice_ai', models.DecimalField(decimal_places=5, max_digits=10, null=True)),
                ('variant', models.ForeignKey(db_column='variant', on_delete=django.db.models.deletion.CASCADE, to='ibvl.variant')),
            ],
            options={
                'db_table': 'snvs',
            },
        ),
        migrations.CreateModel(
            name='VariantAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hgvsp', models.CharField(blank=True, max_length=255, null=True)),
                ('polyphen', models.CharField(blank=True, max_length=255, null=True)),
                ('sift', models.CharField(blank=True, max_length=255, null=True)),
                ('variant_transcript', models.ForeignKey(db_column='variant_transcript', on_delete=django.db.models.deletion.CASCADE, to='ibvl.varianttranscript')),
                ('impact', models.CharField(blank=True, choices=[('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low'), ('MODIFIER', 'Modifier'), ('', '(unknown)')], default='', max_length=20)),
            ],
            options={
                'db_table': 'variants_annotations',
                'verbose_name_plural': 'Variant Annotations',
            },
        ),
        migrations.CreateModel(
            name='VariantConsequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.ForeignKey(db_column='severity', on_delete=django.db.models.deletion.CASCADE, to='ibvl.severity')),
                ('variant_transcript', models.ForeignKey(db_column='variant_transcript', on_delete=django.db.models.deletion.CASCADE, to='ibvl.varianttranscript')),
            ],
            options={
                'db_table': 'variants_consequences',
                'verbose_name_plural': 'Variant Consequences',
            },
        ),
        migrations.AlterModelTable(
            name='gene',
            table='genes',
        ),
    ]
