# Generated by Django 4.2.1 on 2024-03-20 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ibvl', '0002_genomicgnomadfrequency_af_popmax_variant_filter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genomicgnomadfrequency',
            options={'verbose_name_plural': 'Genomic Gnomad Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='genomicibvlfrequency',
            options={'verbose_name_plural': 'Genomic IBVL Frequencies'},
        ),
        migrations.AlterModelOptions(
            name='severity',
            options={'verbose_name_plural': 'Severities'},
        ),
        migrations.AlterModelOptions(
            name='variantannotation',
            options={'verbose_name_plural': 'Variant Annotations'},
        ),
        migrations.AlterModelOptions(
            name='variantconsequence',
            options={'verbose_name_plural': 'Variant Consequences'},
        ),
        migrations.AlterModelOptions(
            name='varianttranscript',
            options={'verbose_name_plural': 'Variant Transcripts'},
        ),
        migrations.RenameField(
            model_name='snv',
            old_name='var_type',
            new_name='type',
        ),
        migrations.AddField(
            model_name='transcript',
            name='biotype',
            field=models.CharField(blank=True, choices=[('protein_coding', 'protein_coding'), ('protein_coding_CDS_not_defined', 'protein_coding_CDS_not_defined'), ('protein_coding_LoF', 'protein_coding_LoF'), ('nonsense_mediated_decay', 'nonsense_mediated_decay'), ('non_stop_decay', 'non_stop_decay'), ('retained_intron', 'retained_intron'), ('processed_transcript', 'processed_transcript'), ('processed_pseudogene', 'processed_pseudogene'), ('pseudogene', 'pseudogene'), ('transcribed_processed_pseudogene', 'transcribed_processed_pseudogene'), ('transcribed_unitary_pseudogene', 'transcribed_unitary_pseudogene'), ('transcribed_unprocessed_pseudogene', 'transcribed_unprocessed_pseudogene'), ('translated_processed_pseudogene', 'translated_processed_pseudogene'), ('TR_C_gene', 'TR_C_gene'), ('TR_D_gene', 'TR_D_gene'), ('TR_J_gene', 'TR_J_gene'), ('TR_J_pseudogene', 'TR_J_pseudogene'), ('TR_V_gene', 'TR_V_gene'), ('TR_V_pseudogene', 'TR_V_pseudogene'), ('unitary_pseudogene', 'unitary_pseudogene'), ('unprocessed_pseudogene', 'unprocessed_pseudogene'), ('IG_C_gene', 'IG_C_gene'), ('IG_C_pseudogene', 'IG_C_pseudogene'), ('IG_D_gene', 'IG_D_gene'), ('IG_J_gene', 'IG_J_gene'), ('IG_J_pseudogene', 'IG_J_pseudogene'), ('IG_pseudogene', 'IG_pseudogene'), ('IG_V_gene', 'IG_V_gene'), ('IG_V_pseudogene', 'IG_V_pseudogene'), ('lncRNA', 'lncRNA'), ('miRNA', 'miRNA'), ('misc_RNA', 'misc_RNA'), ('Mt_rRNA', 'Mt_rRNA'), ('Mt_tRNA', 'Mt_tRNA'), ('ribozyme', 'ribozyme'), ('rRNA', 'rRNA'), ('rRNA_pseudogene', 'rRNA_pseudogene'), ('scaRNA', 'scaRNA'), ('scRNA', 'scRNA'), ('snoRNA', 'snoRNA'), ('snRNA', 'snRNA'), ('sRNA', 'sRNA'), ('vault_RNA', 'vault_RNA'), ('TEC', 'TEC'), ('artifact', 'artifact'), ('', '(unknown)')], default='', max_length=60),
        ),
        migrations.AddField(
            model_name='variantannotation',
            name='impact',
            field=models.CharField(blank=True, choices=[('HIGH', 'High'), ('MODERATE', 'Moderate'), ('LOW', 'Low'), ('MODIFIER', 'Modifier'), ('', '(unknown)')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='genomicgnomadfrequency',
            name='af_popmax',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='genomicgnomadfrequency',
            name='variant',
            field=models.ForeignKey(db_column='variant', on_delete=django.db.models.deletion.CASCADE, to='ibvl.variant'),
        ),
        migrations.AlterField(
            model_name='genomicibvlfrequency',
            name='ac_xx',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='genomicibvlfrequency',
            name='ac_xy',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='genomicibvlfrequency',
            name='af_xx',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='genomicibvlfrequency',
            name='af_xy',
            field=models.DecimalField(decimal_places=10, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='genomicibvlfrequency',
            name='an_tot',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='genomicibvlfrequency',
            name='an_xx',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='genomicibvlfrequency',
            name='an_xy',
            field=models.DecimalField(decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='genomicibvlfrequency',
            name='variant',
            field=models.ForeignKey(db_column='variant', on_delete=django.db.models.deletion.CASCADE, to='ibvl.variant'),
        ),
        migrations.AlterField(
            model_name='snv',
            name='cadd_intr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='snv',
            name='cadd_score',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='snv',
            name='clinvar_url',
            field=models.CharField(blank=True, default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='snv',
            name='clinvar_vcv',
            field=models.DecimalField(decimal_places=3, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='snv',
            name='dbsnp_id',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='snv',
            name='dbsnp_url',
            field=models.CharField(blank=True, default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='snv',
            name='ensembl_url',
            field=models.CharField(blank=True, default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='snv',
            name='gnomad_url',
            field=models.CharField(blank=True, default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='snv',
            name='splice_ai',
            field=models.DecimalField(decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='snv',
            name='ucsc_url',
            field=models.CharField(blank=True, default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='snv',
            name='variant',
            field=models.ForeignKey(db_column='variant', on_delete=django.db.models.deletion.CASCADE, to='ibvl.variant'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='gene',
            field=models.ForeignKey(db_column='gene', on_delete=django.db.models.deletion.CASCADE, to='ibvl.gene'),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='transcript_type',
            field=models.CharField(choices=[('E', 'Ensembl'), ('R', 'Refseq')], max_length=1),
        ),
        migrations.AlterField(
            model_name='transcript',
            name='tsl',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='variant',
            name='filter',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='variantannotation',
            name='variant_transcript',
            field=models.ForeignKey(db_column='variant_transcript', on_delete=django.db.models.deletion.CASCADE, to='ibvl.varianttranscript'),
        ),
        migrations.AlterField(
            model_name='variantconsequence',
            name='severity',
            field=models.ForeignKey(db_column='severity', on_delete=django.db.models.deletion.CASCADE, to='ibvl.severity'),
        ),
        migrations.AlterField(
            model_name='variantconsequence',
            name='variant_transcript',
            field=models.ForeignKey(db_column='variant_transcript', on_delete=django.db.models.deletion.CASCADE, to='ibvl.varianttranscript'),
        ),
        migrations.AlterField(
            model_name='varianttranscript',
            name='transcript',
            field=models.ForeignKey(db_column='transcript', on_delete=django.db.models.deletion.CASCADE, to='ibvl.transcript'),
        ),
        migrations.AlterField(
            model_name='varianttranscript',
            name='variant',
            field=models.ForeignKey(db_column='variant', on_delete=django.db.models.deletion.CASCADE, to='ibvl.variant'),
        ),
        migrations.AlterModelTable(
            name='gene',
            table='genes',
        ),
    ]
