# Generated by Django 4.0 on 2024-05-24 23:15

from django.db import migrations, models
import django.db.models.deletion

def add_profiles(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('ibvl', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.create(user=user)

class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ibvl', '0004_rename_genomicibvlfrequency_genomicvariomefrequency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesses_per_day', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.user')),
            ],
            options={
                'verbose_name_plural': 'Profiles',
                'db_table': 'user_profile',
            },
        ),
        migrations.RunPython(add_profiles)
    ]
