# Generated by Django 4.2.13 on 2024-11-01 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("library", "0009_alter_genomicvariomefrequency_ac_tot_and_more"),
        ("ibvl", "0005_remove_genomicgnomadfrequency_variant_and_more"),
    ]
    
    def create_singleton_instance(apps, schema_editor):
        from ibvl.models.variome_settings import VariomeSettings
        VariomeSettings(site_title="He Kākano").save()
        
    def remove(apps, schema_editor):
        try:
            from ibvl.models.variome_settings import VariomeSettings
            VariomeSettings.objects.all().delete()
        except: 
            pass
        
    operations = [
        migrations.CreateModel(
            name="VariomeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_title", models.CharField(max_length=255)),
                (
                    "example_snv",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="library.variant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.RunPython(create_singleton_instance, remove),
    ]
